### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by purpleKarrot** [ryppl/Boost2Git#13]
The current algorithm to find a match rule is quite slow. It loops linearly through all match rules and checks a) the minimum revision, b) the maximum revision, and c) the prefix. The **first** rule that matches will be chosen, hence the order is relevant.

Searching for the **longest** prefix instead of the **first** prefix can improve both performance (eg by using a radix tree) and usability (repositories.txt may list repositories in any order (currently graph_parallel must come before graph)).

**Comment by dabrahams** [comment]
I got a start on this in d4fcdb2, but it needs to be debugged and then hooked up to the rest of the program.  I think it's pretty close.  It would be great if you could carry it forward, Daniel.

**Comment by dabrahams** [comment]
Bugs are fixed now, I think

**Comment by dabrahams** [comment]
OK, there's a patricia trie implementation there now, but now I realize that's not enough because it doesn't deal with minimum and maximum revisions.  I think augmenting the patricia trie with revision ranges might be possible, but I'm out of time to think about it right now.
