### ISSUE TITLE
deal with dir_it

### ISSUE THREAD

**Issue by dabrahams** [ryppl/Boost2Git#14]
The reason it's failing to push is that the master branch really is gone.  See [here](http://ci.boost.org/websvn/log.php?repname=repos+1&path=%2Ftrunk%2Fboost%2Flibs%2Fdir_it%2F&isdir=1&peg=14715&sr=&er=1&max=40&search=&all=1) or [here](http://ci.boost.org/svn-trac/log/boost%20SVN/trunk/boost/libs/dir_it?rev=8166)

**Comment by dabrahams** [comment]
I think, when the master branch is deleted, it should be replaced with a single commit containing a README that says it was deleted... or possibly, that last commit should be ignored and it should simply be removed from the super-module

**Comment by purpleKarrot** [comment]
I compeltely agree.

2013/3/9 Dave Abrahams notifications@github.com

**Comment by dabrahams** [comment]
Is this bug fixed now?

**Comment by purpleKarrot** [comment]
Pushing no longer fails, since we don't delete master. There is no README saying it was deleted.

**Comment by purpleKarrot** [comment]
dir_it has been moved to the sandbox.
