### ISSUE TITLE
cleanup/refactor SvnRevision class

### ISSUE THREAD

**Issue by purpleKarrot** [ryppl/Boost2Git#16]
the implementation of that closs by now is full of redundant checks and dead branches.

**Comment by dabrahams** [comment]
I think e5a08b7394d1 may have introduced some redundant calls to pathExists.

On Wed, Apr 17, 2013 at 12:31 PM, Daniel Pfeifer
notifications@github.comwrote:

> the implementation of that closs by now is full of redundant checks and
> dead branches.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ryppl/Boost2Git/issues/16
> .

## 

Dave Abrahams

**Comment by dabrahams** [comment]
Should this be closed now or is it still a problem?

**Comment by dabrahams** [comment]
Closing as the files in question died in the rewrite
