### ISSUE TITLE
Put information about line numbers into ruleset

### ISSUE THREAD

**Issue by dabrahams** [ryppl/Boost2Git#19]
Useful diagnostics from svn2git would be a whole lot more useful if the ruleset contained line number information about the participating rules.  I tried to implement this myself but couldn't figure it out.  Assigning to @purpleKarrot since he's the one with the Spirit chops.

**Comment by purpleKarrot** [comment]
inplemented in c36938b316b1c11d53ca6d425143359fcfc2bee6.
