### ISSUE TITLE
Incremental conversion breaks .gitmodules

### ISSUE THREAD

**Issue by purpleKarrot** [ryppl/Boost2Git#21]
It seams the information about existing submodules is lost when doing an incremental Boost2git conversion.

Workaround: Run a full conversion.
Solution: Read the .gitmodules file on startup.

**Comment by dabrahams** [comment]
I'm working on a fix for this that uses the logfile the same way that the rest of the incremental resumption stuff works.

**Comment by dabrahams** [comment]
Oops, this was actually fixed by commit e13e87a
