### ISSUE TITLE
Support for tags

### ISSUE THREAD

**Issue by purpleKarrot** [ryppl/Boost2Git#4]
Make sure tags are created correctly.

**Comment by purpleKarrot** [comment]
In Svn2Git, tags are listed as branches with the name "refs/tags/<tagname>".

Our DSL makes the distinction between branches and tags explicit (the "refs/tags/" prefix should be omitted).

Internally, we could simply add the prefix and use the old Svn2Git code, or invest some more refactoring.

**Comment by dabrahams** [comment]
Doesn't seem to be working.  Needs examination

**Comment by dabrahams** [comment]
I think it's working now.  If evidence is found to the contrary, please reopen
